# Generated by Django 5.2.9 on 2026-01-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_tr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='district_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='district_name_tr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='descriptions_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='descriptions_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title_tr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_tr',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
