# Generated by Django 5.2.9 on 2026-01-21 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_city_city_name_en_city_city_name_tr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.region'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_region', to='house_app.region'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_city', to='house_app.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_place', to='house_app.district'),
        ),
        migrations.AlterField(
            model_name='propertyimg',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_img', to='house_app.property'),
        ),
    ]
