# Generated by Django 5.2.9 on 2026-01-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0003_district_region_alter_city_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.PositiveSmallIntegerField(default=True),
        ),
    ]
