# Generated by Django 5.2.9 on 2026-01-21 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0004_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_property', to='house_app.property'),
        ),
    ]
